### ISSUE TITLE
Frequency offset not working 

### ISSUE THREAD

**Issue by righthalfplane** [glv2/ofdm-transfer#2]
I tried your example and the same example with a minus offset -

ofdm-transfer -t -r driver=hackrf -s 4000000 -f 434000000 -o 100000 -b 9600 -g 30 -w 1 LICENSE

ofdm-transfer -t -r driver=hackrf -s 4000000 -f 434000000 -o -100000 -b 9600 -g 30 -w 1 LICENSE

The transmitting frequency did not change, but a small signal appeared at +- 100000 hz

I have attach screen captures -

![offsetMinus](https://user-images.githubusercontent.com/36057033/202738307-a709f75f-395b-4b55-8059-a998cdb8b299.png)

![offsetPlus](https://user-images.githubusercontent.com/36057033/202738370-499dd478-fbae-450e-a00d-a2a9b576283a.png)

**Comment by glv2** [comment]
The OFDM signal will always be at the frequency specified with the '-f' option.
What the '-o' option does is set the central frequency of the HackRF away from the OFDM signal frequency. It is useful to move the central DC spike generated by the HackRF (the small signal at +- 100 kHz in your screenshots) out of the useful signal and prevent it from interfering.

**Comment by righthalfplane** [comment]
Ok Thanks, I miss understood the option - thought that you were going shift the center frequency by that amount and leave the spike behind at the -f frequency.

**Comment by glv2** [comment]
Ok. Closing.
